#!/usr/bin/env python3
"""Generate the Bun-side mirror of the canonical Python TUI name contract."""

import argparse
from pathlib import Path

from workgate.ui.contracts import (
    POSIX_TUI_EXECUTABLE_NAME,
    WINDOWS_TUI_EXECUTABLE_NAME,
)

REPO = Path(__file__).resolve().parents[2]
OUTPUT = REPO / "ui-opentui" / "scripts" / "executable-contract.ts"


def render_contract() -> str:
    """Render the deterministic TypeScript mirror consumed by Bun builds."""
    return (
        "// Generated by scripts/generation/generate-tui-executable-contract.py; do not edit.\n"
        f'export const POSIX_TUI_EXECUTABLE_NAME = "{POSIX_TUI_EXECUTABLE_NAME}"\n'
        f'export const WINDOWS_TUI_EXECUTABLE_NAME = "{WINDOWS_TUI_EXECUTABLE_NAME}"\n'
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render_contract()
    if args.check:
        actual = (
            OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None
        )
        if actual != expected:
            print(
                "Generated TUI executable contract is stale; run "
                "`uv run python scripts/generation/generate-tui-executable-contract.py`."
            )
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
