// Generated by scripts/generation/generate-tui-executable-contract.py; do not edit.
export const POSIX_TUI_EXECUTABLE_NAME = "workgate-tui"
export const WINDOWS_TUI_EXECUTABLE_NAME = "workgate-tui.exe"
