// Generated by scripts/generation/generate-tui-executable-contract.py; do not edit.
export const POSIX_TUI_EXECUTABLE_NAME = "local-shell-mcp-tui"
export const WINDOWS_TUI_EXECUTABLE_NAME = "local-shell-mcp-tui.exe"
